import { useEffect, useState } from "react";
import { Link, useSearchParams } from "react-router-dom";
import { ArrowUpRight, Download, RotateCcw, Calculator, CarFront, Check, Wallet } from "lucide-react";
import { vehicles } from "../data";
import { calculatePayment, money, type PaymentInputs } from "../sales";
import { saveText } from "../lib";
import { Intro, Eyebrow, DemoNote } from "../components/UI";
import { MediaSlot } from "../components/Media";
type Form = Record<keyof PaymentInputs, string>;
const defaults = (price: number): Form => ({ price: String(price), down: "5000", trade: "0", owing: "0", fees: "0", tax: "0", apr: "6.9", months: "60" });
function NumberField({ label, name, value, onChange, max = 10000000 }: { label: string; name: keyof Form; value: string; onChange: (key: keyof Form, value: string) => void; max?: number }) { return <label className="sales-field">{label}<input type="number" inputMode="decimal" min="0" max={max} step="0.01" value={value} onChange={e => onChange(name, e.target.value)} /></label>; }
const tabs = [{ id: "payment", label: "Payment studio", Icon: Calculator }, { id: "trade", label: "Trade-in notebook", Icon: CarFront }, { id: "cash", label: "Cash & buying steps", Icon: Wallet }];
export default function Buying() {
  const [params, setParams] = useSearchParams(); const vehicle = vehicles.find(v => v.id === params.get("vehicle")) || vehicles[0];
  const tab = tabs.some(t => t.id === params.get("tab")) ? params.get("tab")! : "payment";
  const [form, setForm] = useState<Form>(() => defaults(vehicle.price)); const [tradeCar, setTradeCar] = useState(""); const [tradeNotes, setTradeNotes] = useState(""); const [tradeCondition, setTradeCondition] = useState("To be inspected");
  useEffect(() => { setForm(f => ({ ...f, price: String(vehicle.price) })); }, [vehicle.id, vehicle.price]);
  const change = (name: keyof Form, value: string) => setForm(f => ({ ...f, [name]: value }));
  const query = (key: string, value: string) => { const next = new URLSearchParams(params); next.set(key, value); setParams(next, { replace: true }); };
  let error = "", result: ReturnType<typeof calculatePayment> | null = null;
  const input = Object.fromEntries(Object.entries(form).map(([k, v]) => [k, Number(v)])) as unknown as PaymentInputs;
  try { if (Object.values(form).some(v => v.trim() === "") || Object.values(input).some(v => v > 10000000)) throw new Error("Complete all amounts with valid, non-negative numbers."); result = calculatePayment(input); } catch (e) { error = e instanceof Error ? e.message : "Check your amounts."; }
  const assumptions = "ILLUSTRATION ONLY. Fictional vehicle and sample CAD amounts. Not a quote, credit application, lender offer, approval, or appraisal. Monthly amortization with a fixed entered APR; actual lender calculations may differ. Tax is calculated on the vehicle price only; jurisdiction-specific trade-in credits and tax on fees are not modeled. Confirm all amounts and terms with the actual seller and lender.";
  const download = () => { if (!result) return; saveText("vehiclesite-payment-scenario.txt", ["VEHICLESITE / PERSONAL PAYMENT SCENARIO", "DEMO — NOT AN OFFER", "", `${vehicle.year} ${vehicle.name} (fictional listing)`, ...Object.entries(input).map(([k,v]) => `${k}: ${v}`), "", `Illustrative amount financed: ${money(result.principal, 2)}`, `Illustrative monthly payment: ${money(result.monthly, 2)}`, `Total loan payments: ${money(result.loanTotal, 2)}`, `Total interest: ${money(result.interest, 2)}`, `Net trade equity: ${money(result.equity, 2)}`, "", assumptions].join("\n")); };
  return <><Intro number="02" label="Buying tools" title="The numbers." italic="On your terms." copy="A space to explore—not apply. Adjust a payment scenario, prepare a trade-in conversation, and map out what happens before the keys become yours." /><section className="container sales-buying"><DemoNote>Local tools only. No credit checks, lender connections, offers, appraisals, or personal-data submissions.</DemoNote><div className="sales-tabs" role="tablist" aria-label="Buying tools">{tabs.map(({ id, label, Icon }, i) => <button key={id} id={`buy-tab-${id}`} role="tab" aria-selected={tab === id} aria-controls={`buy-panel-${id}`} tabIndex={tab === id ? 0 : -1} onClick={() => query("tab", id)} onKeyDown={e => { const n = e.key === "ArrowRight" ? (i + 1) % tabs.length : e.key === "ArrowLeft" ? (i + tabs.length - 1) % tabs.length : e.key === "Home" ? 0 : e.key === "End" ? tabs.length - 1 : -1; if (n >= 0) { e.preventDefault(); query("tab", tabs[n].id); document.getElementById(`buy-tab-${tabs[n].id}`)?.focus(); } }}><Icon size={18} />{label}</button>)}</div><div className="sales-buy-grid"><div role="tabpanel" id={`buy-panel-${tab}`} aria-labelledby={`buy-tab-${tab}`} className="sales-tool-panel"><label className="sales-field">Start with a sample car<select value={vehicle.id} onChange={e => query("vehicle", e.target.value)}>{vehicles.map(v => <option value={v.id} key={v.id}>{v.year} {v.name} · {money(v.price)}</option>)}</select></label>
  {tab === "payment" && <><Eyebrow>Make a scenario, not a commitment</Eyebrow><h2>What could<br /><em>monthly look like?</em></h2><div className="sales-form-grid"><NumberField label="Vehicle price (CAD)" name="price" value={form.price} onChange={change} /><NumberField label="Down payment (CAD)" name="down" value={form.down} onChange={change} /><NumberField label="Assumed trade-in value (CAD)" name="trade" value={form.trade} onChange={change} /><NumberField label="Amount owing on trade-in (CAD)" name="owing" value={form.owing} onChange={change} /><NumberField label="Estimated fees (CAD)" name="fees" value={form.fees} onChange={change} /><NumberField label="Tax rate (%) — enter your own" name="tax" value={form.tax} onChange={change} max={100} /><NumberField label="APR (%) — illustrative" name="apr" value={form.apr} onChange={change} max={100} /><label className="sales-field">Loan term<select value={form.months} onChange={e => change("months", e.target.value)}>{[24,36,48,60,72,84].map(n => <option key={n} value={n}>{n} months</option>)}</select></label></div><p className="sales-fineprint">The starting 6.9% APR is an invented example, not an available rate. Tax defaults to 0% because no jurisdiction is configured. Enter an appropriate estimate; this is not a regional tax calculator.</p><button className="text-link" onClick={() => setForm(defaults(vehicle.price))}><RotateCcw size={14} />Reset this scenario</button></>}
  {tab === "trade" && <><Eyebrow>A better appraisal conversation</Eyebrow><h2>Your current car.<br /><em>Part of the picture.</em></h2><p>No invented instant valuation. Capture your own assumptions, understand positive or negative equity, and prepare details for a real appraisal.</p><label className="sales-field">Your trade-in (optional)<input value={tradeCar} maxLength={100} placeholder="Year, make, model — no VIN or personal details" onChange={e => setTradeCar(e.target.value)} /></label><div className="sales-form-grid"><NumberField label="Your assumed trade-in value (CAD)" name="trade" value={form.trade} onChange={change} /><NumberField label="Amount still owing (CAD)" name="owing" value={form.owing} onChange={change} /></div><label className="sales-field">Your condition notes<select value={tradeCondition} onChange={e => setTradeCondition(e.target.value)}><option>To be inspected</option><option>Minor cosmetic wear to discuss</option><option>Repairs or damage to discuss</option><option>Service history to review</option></select></label><label className="sales-field">Questions for the appraiser<textarea rows={4} maxLength={800} value={tradeNotes} placeholder="Mileage, service records, tires, repairs, extra keys… Avoid personal or financial account details." onChange={e => setTradeNotes(e.target.value)} /></label><div className="sales-equity"><span className="micro">YOUR ASSUMPTIONS / NET EQUITY</span><strong>{result ? money(result.equity) : "—"}</strong><p>{result && result.equity < 0 ? "Your assumed balance is greater than your assumed trade value. This example adds the difference to the amount financed; a lender may not permit that." : "Assumed trade value minus the amount owing. This is not an appraisal or guaranteed credit."}</p></div><button className="button button-gold" disabled={!result} onClick={() => saveText("vehiclesite-trade-in-notebook.txt", ["VEHICLESITE / TRADE-IN DISCUSSION DRAFT", "Not a valuation, appraisal, or offer.", `Car: ${tradeCar || "Not entered"}`, `Condition notes: ${tradeCondition}`, `Assumed value: ${form.trade} CAD`, `Amount owing: ${form.owing} CAD`, `Assumed equity: ${result ? money(result.equity, 2) : "Not calculated"}`, `Questions: ${tradeNotes || "None entered"}`, "", "Ask the seller for an inspection and written appraisal. No information has been submitted."].join("\n"))}><Download size={16} />Download my trade-in notes</button><Link className="text-link" to="/documents/purchase-options">Trade-in preparation template<ArrowUpRight size={15} /></Link></>}
  {tab === "cash" && <><Eyebrow>From first look to first drive</Eyebrow><h2>A clear path.<br /><em>No skipped details.</em></h2><p>A cash purchase still deserves a complete written breakdown. The estimate at right is not a dealer quote; approved prices, tax, fees, and terms belong in the actual sale documents.</p><div className="sales-ownership-steps">{[["01", "Find your fit", "Shortlist cars and compare the details you use every day."], ["02", "See the actual car", "Arrange a test drive and ask about history, condition, and inspection records."], ["03", "Get the full written picture", "Ask for the complete price, any trade-in appraisal, and applicable terms."], ["04", "Prepare for the handover", "Agree the date and confirm which documents and payment arrangements are needed."]].map(([n, title, text]) => <div key={n}><span>{n}</span><div><h3>{title}</h3><p>{text}</p></div></div>)}</div><Link className="button button-gold" to="/documents/purchase-options">Explore purchase documents<ArrowUpRight size={16} /></Link><button className="text-link" onClick={() => query("tab", "payment")}>Adjust the price, tax, and fee assumptions<ArrowUpRight size={15} /></button></>}
  </div><aside className="sales-payment-summary" aria-label="Payment scenario summary"><div className="sales-summary-car"><MediaSlot vehicle={vehicle} /><span className="micro">{vehicle.year} / {vehicle.stockNumber}</span><h3>{vehicle.name}</h3></div><span className="micro">{tab === "cash" ? "ILLUSTRATIVE PURCHASE TOTAL" : "ILLUSTRATIVE MONTHLY PAYMENT"}</span><output className="sales-monthly" aria-label={tab === "cash" ? "Estimated purchase total" : "Estimated monthly payment"}>{result ? money(tab === "cash" ? result.purchaseTotal : result.monthly, 2) : "—"}<small>{tab === "cash" ? "CAD · before trade / down payment" : `CAD / month · ${form.months || "—"} months`}</small></output>{error ? <p className="form-error" role="alert">{error}</p> : result && <><dl className="sales-breakdown"><div><dt>Entered vehicle price</dt><dd>{money(input.price, 2)}</dd></div><div><dt>Estimated tax & fees</dt><dd>{money(result.taxAmount + input.fees, 2)}</dd></div><div><dt>Down payment</dt><dd>{money(input.down, 2)}</dd></div><div><dt>Net trade equity</dt><dd>{money(result.equity, 2)}</dd></div><div><dt>Amount financed</dt><dd>{money(result.principal, 2)}</dd></div><div><dt>Total loan payments</dt><dd>{money(result.loanTotal, 2)}</dd></div><div><dt>Total loan interest</dt><dd>{money(result.interest, 2)}</dd></div></dl>{result.excess > 0 && <p className="form-error">Your down payment and equity exceed this purchase total by {money(result.excess, 2)}. Reduce an assumption; no refund is promised.</p>}</>}<button className="button button-subtle" disabled={!result} onClick={download}><Download size={15} />Save this scenario</button><Link className="button button-gold" to={`/pickup?vehicle=${vehicle.id}&purpose=test-drive`}>Explore a visit draft<ArrowUpRight size={15} /></Link><p className="sales-fineprint">{assumptions}</p><span className="sales-private"><Check size={13} />No credit check. Nothing submitted.</span></aside></div></section></>;
}
