import { useEffect, useRef, useState } from "react";
import { Link, useSearchParams } from "react-router-dom";
import { ArrowLeft, ArrowUpRight, CalendarDays, Check, Download, KeyRound, CarFront } from "lucide-react";
import { vehicles, pickupChecklist, testDriveChecklist } from "../data";
import { dayFromToday, formatDay, visitDateValid, makeCalendar } from "../sales";
import { saveText } from "../lib";
import { Intro, Eyebrow, DemoNote } from "../components/UI";
import { MediaSlot } from "../components/Media";
export default function Pickup() {
  const [params, setParams] = useSearchParams(); const purpose = params.get("purpose") === "pickup" ? "pickup" : "test-drive"; const purposeName = purpose === "pickup" ? "Vehicle pickup" : "Test drive";
  const vehicle = vehicles.find(v => v.id === params.get("vehicle")) || vehicles[0];
  const [step, setStep] = useState(1); const [date, setDate] = useState(dayFromToday(1)); const [time, setTime] = useState("10:00"); const [notes, setNotes] = useState(""); const [checked, setChecked] = useState<number[]>([]); const [error, setError] = useState(""); const [exported, setExported] = useState(false); const heading = useRef<HTMLHeadingElement>(null);
  const checklist = purpose === "pickup" ? pickupChecklist : testDriveChecklist; const zone = Intl.DateTimeFormat().resolvedOptions().timeZone || "your device's local time zone";
  useEffect(() => { setStep(1); setChecked([]); setError(""); setExported(false); }, [purpose, vehicle.id]);
  useEffect(() => { if (step > 1) heading.current?.focus({ preventScroll: true }); }, [step]);
  const query = (key: string, value: string) => { const next = new URLSearchParams(params); next.set(key, value); setParams(next, { replace: true }); };
  const validate = () => { if (vehicle.stock !== "Available") return "This sample car is not available for visit planning. Choose an available example."; if (!visitDateValid(date, time) || date > dayFromToday(90)) return "Choose a valid future date and time within the next 90 days."; return ""; };
  const next = () => { const message = validate(); setError(message); if (!message) setStep(s => Math.min(3, s + 1)); };
  const draftText = () => ["VEHICLESITE / PERSONAL VISIT DRAFT", "UNCONFIRMED — NOT A BOOKING", "", `Purpose: ${purposeName}`, `Fictional car: ${vehicle.year} ${vehicle.name} (${vehicle.stockNumber})`, `Preferred date: ${date}`, `Preferred time: ${time}`, `Time zone: ${zone}`, "Location: To be confirmed with the seller", "", "Preparation checklist (discussion points, not official requirements):", ...checklist.map((item, i) => `${checked.includes(i) ? "[x]" : "[ ]"} ${item}`), "", `Notes: ${notes || "None entered"}`, "", "DEMO ONLY. No appointment, vehicle hold, purchase, or dealer notification has been created. Confirm the actual vehicle, date, time, location, and requirements directly with the seller."].join("\n");
  const exportDraft = (calendar: boolean) => { const message = validate(); if (message) { setError(message); setStep(1); return; } if (calendar) saveText(`vehiclesite-unconfirmed-${purpose}.ics`, makeCalendar(date, time, purposeName, vehicle.name, notes), "text/calendar"); else saveText("vehiclesite-visit-draft.txt", draftText()); setExported(true); };
  return <><Intro number="03" label="Pickup & test drives" title="The keys." italic="A date to remember." copy="Plan the first drive or the day you bring it home. Choose a preferred date, get organized, and create a personal draft to discuss with the seller." /><section className="container sales-pickup"><DemoNote>Dates and times are preferences, not real availability. Nothing is booked, reserved, or sent to a dealership.</DemoNote><div className="sales-visit-grid"><div className="sales-visit-builder"><ol className="sales-stepper" aria-label="Visit planning progress">{["Your visit", "Get ready", "Your draft"].map((label, i) => <li key={label} className={step === i + 1 ? "current" : step > i + 1 ? "complete" : ""} aria-current={step === i + 1 ? "step" : undefined}><span>{step > i + 1 ? <Check size={13} /> : `0${i + 1}`}</span>{label}</li>)}</ol>
  {step === 1 && <div className="sales-visit-step"><Eyebrow>01 / Picture the moment</Eyebrow><h2 ref={heading} tabIndex={-1}>What brings<br /><em>you in?</em></h2><div className="sales-purpose" role="group" aria-label="Visit purpose"><button className={purpose === "test-drive" ? "active" : ""} aria-pressed={purpose === "test-drive"} onClick={() => query("purpose", "test-drive")}><CarFront size={23} /><strong>Test drive</strong><span>Get a feel for your next car.</span></button><button className={purpose === "pickup" ? "active" : ""} aria-pressed={purpose === "pickup"} onClick={() => query("purpose", "pickup")}><KeyRound size={23} /><strong>Vehicle pickup</strong><span>Plan the handover day.</span></button></div><label className="sales-field">Your sample vehicle<select value={vehicle.id} onChange={e => query("vehicle", e.target.value)}>{vehicles.map(v => <option key={v.id} value={v.id} disabled={v.stock !== "Available"}>{v.year} {v.name}{v.stock !== "Available" ? ` · ${v.stock} (visits disabled)` : ""}</option>)}</select></label><label className="sales-field">Preferred date<input type="date" value={date} min={dayFromToday(0)} max={dayFromToday(90)} onChange={e => { setDate(e.target.value); setError(""); }} /></label><div className="sales-date-rail" role="group" aria-label="Suggested dates, not availability">{Array.from({ length: 7 }, (_, i) => dayFromToday(i + 1)).map(day => { const d = new Date(`${day}T12:00:00`); return <button key={day} aria-label={formatDay(day)} aria-pressed={date === day} className={date === day ? "active" : ""} onClick={() => { setDate(day); setError(""); }}><span>{d.toLocaleDateString("en-CA", { weekday: "short" })}</span><strong>{d.getDate()}</strong><small>{d.toLocaleDateString("en-CA", { month: "short" })}</small></button>; })}</div><fieldset className="sales-time-field"><legend>Preferred time · {zone}</legend><div className="sales-time-options">{["10:00", "11:30", "13:00", "14:30", "16:00"].map(slot => <label key={slot} className={time === slot ? "active" : ""}><input type="radio" name="preferred-time" value={slot} checked={time === slot} onChange={() => { setTime(slot); setError(""); }} />{slot}</label>)}</div></fieldset><p className="sales-fineprint">Suggested dates and times are not a dealership schedule. Confirm opening hours, appointment length, and the actual vehicle separately. This draft uses your device's time zone.</p></div>}
  {step === 2 && <div className="sales-visit-step"><Eyebrow>02 / A little preparation</Eyebrow><h2 ref={heading} tabIndex={-1}>{purpose === "pickup" ? "Make the handover" : "Make the first drive"}<br /><em>feel easy.</em></h2><p>Use these as discussion prompts. The seller must confirm the actual requirements. Nothing here is mandatory to create your draft.</p><div className="sales-readiness" aria-label={`${checked.length} of ${checklist.length} preparation items checked`}><span className="sales-readiness-ring" style={{ "--ready": `${checked.length / checklist.length * 100}%` } as React.CSSProperties}>{checked.length}/{checklist.length}</span><div><strong>Your preparation checklist</strong><p>Check the points you have considered.</p></div></div><div className="sales-checklist">{checklist.map((item, i) => <label key={item}><input type="checkbox" checked={checked.includes(i)} onChange={e => setChecked(e.target.checked ? [...checked, i] : checked.filter(n => n !== i))} /><span>{item}</span></label>)}</div><label className="sales-field">Notes for your own visit draft<textarea rows={4} maxLength={800} value={notes} onChange={e => setNotes(e.target.value)} placeholder="Questions, features to try, things to confirm. Avoid sensitive personal information." /></label><Link className="text-link" to={purpose === "pickup" ? "/documents/pickup-essentials" : "/documents/vehicle-records"}>Browse preparation templates<ArrowUpRight size={15} /></Link></div>}
  {step === 3 && <div className="sales-visit-step sales-draft" id="visit-draft"><span className="demo-badge">UNCONFIRMED DRAFT</span><h2 ref={heading} tabIndex={-1}>Your plan.<br /><em>Not a booking.</em></h2><p>Keep this as your starting point. Contact the actual seller to confirm the car, date, time, location, and requirements before travelling.</p><div className="sales-visit-ticket"><div><span className="micro">YOUR NEXT CHAPTER / {purposeName.toUpperCase()}</span><h3>{vehicle.year} {vehicle.name}</h3><p>{formatDay(date)} · {time}<br />{zone}</p></div><KeyRound size={38} /></div><div className="sales-draft-checklist"><strong>Preparation notes</strong>{checklist.map((item, i) => <p key={item}><span aria-label={checked.includes(i) ? "Checked" : "Not checked"}>{checked.includes(i) ? "✓" : "○"}</span>{item}</p>)}</div>{notes && <div className="sales-draft-notes"><strong>Your notes</strong><p>{notes}</p></div>}<div className="sales-export-actions"><button className="button button-gold" onClick={() => exportDraft(true)}><CalendarDays size={16} />Download unconfirmed reminder</button><button className="button button-subtle" onClick={() => exportDraft(false)}><Download size={16} />Download visit draft</button></div><p className="sales-fineprint">The .ics file creates a tentative, personal 45-minute placeholder in your calendar when you import it. It is not an invitation and does not notify the seller. Exported files contain any notes you entered.</p>{exported && <p className="sales-export-notice" role="status"><Check size={16} />Draft exported. No appointment has been booked.</p>}</div>}
  {error && <p className="form-error" role="alert">{error}</p>}<div className="sales-builder-actions">{step > 1 && <button className="text-link" onClick={() => setStep(s => s - 1)}><ArrowLeft size={15} />{step === 3 ? "Edit preparation" : "Back"}</button>}{step < 3 && <button className="button button-gold" onClick={next}>{step === 1 ? "Prepare my visit" : "Review my plan"}<ArrowUpRight size={16} /></button>}{step === 3 && <button className="text-link" onClick={() => { setStep(1); setExported(false); }}>Edit date or vehicle<CalendarDays size={15} /></button>}</div></div><aside className="sales-visit-summary" aria-label="Live visit summary"><MediaSlot vehicle={vehicle} /><div><Eyebrow>Your visit, taking shape</Eyebrow><h3>{vehicle.name}</h3><dl className="sales-breakdown"><div><dt>Purpose</dt><dd>{purposeName}</dd></div><div><dt>Preferred date</dt><dd>{/^\d{4}-\d{2}-\d{2}$/.test(date) ? new Date(`${date}T12:00:00`).toLocaleDateString("en-CA", { month: "short", day: "numeric", year: "numeric" }) : "Choose a date"}</dd></div><div><dt>Preferred time</dt><dd>{time}</dd></div><div><dt>Time zone</dt><dd>{zone}</dd></div><div><dt>Preparation</dt><dd>{checked.length}/{checklist.length} considered</dd></div><div><dt>Appointment status</dt><dd>Not booked</dd></div></dl><p className="sales-fineprint">Your date and notes stay in page memory. Nothing is sent to a dealership. Reloading or leaving this page clears the draft unless you downloaded it.</p><Link className="text-link" to={`/buying?vehicle=${vehicle.id}`}>Explore this car's numbers<ArrowUpRight size={15} /></Link></div></aside></div></section></>;
}
