import { useEffect, useRef, type ReactNode } from "react";
import { Link } from "react-router-dom";
import { ArrowUpRight, Heart, Plus, Check, X, Gauge, CalendarDays } from "lucide-react";
import type { Vehicle } from "../data";
import { MediaSlot } from "./Media";
import { useSite } from "../SiteContext";
import { money, distance } from "../sales";
export function Eyebrow({ children, light = false }: { children: ReactNode; light?: boolean }) { return <div className={`eyebrow ${light ? "eyebrow-light" : ""}`}><span />{children}</div>; }
export function Intro({ number, label, title, italic, copy }: { number: string; label: string; title: string; italic: string; copy: string }) { return <section className="page-intro container"><div className="intro-top"><Eyebrow>{number} / {label}</Eyebrow><span className="micro">VEHICLESITE — SHOWROOM CONCEPT</span></div><div className="intro-main"><h1>{title}<br /><em>{italic}</em></h1><p>{copy}</p></div></section>; }
export function SectionHeading({ label, title, italic, to, link }: { label: string; title: string; italic?: string; to?: string; link?: string }) { return <div className="section-heading"><div><Eyebrow>{label}</Eyebrow><h2>{title} {italic && <em>{italic}</em>}</h2></div>{to && <Link className="text-link" to={to}>{link || "Explore"}<ArrowUpRight size={17} /></Link>}</div>; }
export function DemoNote({ children }: { children?: ReactNode }) { return <div className="sales-demo-note"><span className="demo-badge">DEMO SHOWROOM</span><p>{children || "Fictional cars and sample CAD prices. Tax and fees are not included. No purchases, reservations, or credit applications are made."}</p></div>; }
export function VehicleCard({ vehicle: v, index = 0, journeyActions = false }: { vehicle: Vehicle; index?: number; journeyActions?: boolean }) {
  const { saved, toggleSaved, comparison, toggleComparison, setModal } = useSite();
  const favorite = saved.includes(v.id), compared = comparison.includes(v.id);
  return <article className="vehicle-card reveal" style={{ "--delay": `${index % 3 * 65}ms` } as React.CSSProperties}>
    <div className="vehicle-image"><button className="vehicle-visual-button" aria-label={`View ${v.name}`} onClick={() => setModal({ type: "vehicle", vehicle: v })}><MediaSlot vehicle={v} /></button><span className="vehicle-type">{v.condition} · {v.category}</span><button className={`icon-button save-button ${favorite ? "is-saved" : ""}`} aria-label={`${favorite ? "Unsave" : "Save"} ${v.name}`} aria-pressed={favorite} onClick={() => toggleSaved(v.id)}><Heart size={17} fill={favorite ? "currentColor" : "none"} /></button><span className={`sales-stock stock-${v.stock.toLowerCase()}`}>{v.stock} <small>· sample</small></span></div>
    <div className="vehicle-copy"><div className="vehicle-copy-top"><p className="micro">{v.edition}</p><span className="micro muted">{v.stockNumber}</span></div><button className="vehicle-title" onClick={() => setModal({ type: "vehicle", vehicle: v })}><h3>{v.name}</h3><ArrowUpRight size={20} /></button><div className="vehicle-specs"><span><CalendarDays size={13} />{v.year}</span><span><Gauge size={13} />{distance(v.mileage)}</span><span>{v.power}</span></div><div className="vehicle-bottom"><span className="sale-price">{money(v.price)}<small>Sample CAD · plus tax & fees</small></span><button className={`compare-button ${compared ? "active" : ""}`} aria-label={`${compared ? "Remove" : "Add"} ${v.name} ${compared ? "from" : "to"} comparison`} aria-pressed={compared} onClick={() => toggleComparison(v.id)}>{compared ? <Check size={14} /> : <Plus size={14} />}Compare</button></div>{journeyActions && <div className="vehicle-journey-actions" aria-label={`Next steps for ${v.name}`}><Link className="text-link" to={`/buying?vehicle=${v.id}`}>Explore sample costs<ArrowUpRight size={14} /></Link>{v.stock === "Available" ? <Link className="text-link" to={`/pickup?vehicle=${v.id}&purpose=test-drive`}>Draft a test drive<CalendarDays size={14} /></Link> : <span className="sales-unavailable">Visit unavailable for this sample</span>}</div>}</div>
  </article>;
}
export function JourneyCTA() { return <section className="journey-cta container reveal"><div><Eyebrow>Make it your next chapter</Eyebrow><h2>The right car.<br /><em>Your kind of future.</em></h2></div><div><p>Start with the shortlist. Explore the numbers.<br />Then plan the moment you take the wheel.</p><Link to="/pickup" className="button button-gold">Plan a test drive<ArrowUpRight size={18} /></Link></div><div className="cta-orbit" aria-hidden="true" /></section>; }
export function Dialog({ title, children, onClose, className = "" }: { title: string; children: ReactNode; onClose: () => void; className?: string }) {
  const ref = useRef<HTMLDialogElement>(null);
  useEffect(() => { const dialog = ref.current; const previous = document.activeElement as HTMLElement | null; const overflow = document.body.style.overflow; dialog?.showModal(); document.body.style.overflow = "hidden"; return () => { dialog?.close(); document.body.style.overflow = overflow; if (previous?.isConnected) previous.focus(); }; }, []);
  return <dialog ref={ref} className={`dialog ${className}`} aria-label={title} onCancel={e => { e.preventDefault(); onClose(); }} onClick={e => { if (e.target === e.currentTarget) onClose(); }}><div className="dialog-inner"><div className="dialog-header"><span className="micro">{title}</span><button className="icon-button" aria-label="Close dialog" onClick={onClose}><X size={20} /></button></div>{children}</div></dialog>;
}
