import { useEffect, useRef, useState } from "react";
import { Link, NavLink, Navigate, Route, Routes, useLocation, useNavigate, useSearchParams } from "react-router-dom";
import { ArrowUpRight, ArrowRight, ArrowLeft, Sun, Moon, Search, Menu, X, Heart, Check, SlidersHorizontal, Play, Pause, Command, Plus, Copy, CalendarDays } from "lucide-react";
import { SiteContext, type ModalState, useSite } from "./SiteContext";
import { vehicles, documentGroups, media, navigation, type Vehicle } from "./data";
import { isBoolean, isStrings, isTheme, useStored, publicAsset } from "./lib";
import { money, distance } from "./sales";
import { Dialog, Eyebrow } from "./components/UI";
import { MediaSlot } from "./components/Media";
import Home from "./pages/Home";
import Inventory from "./pages/Inventory";
import Buying from "./pages/Buying";
import Pickup from "./pages/Pickup";
import Documents from "./pages/Documents";
const validSaved = (x: unknown): x is string[] => isStrings(x) && x.every(id => vehicles.some(v => v.id === id)) && new Set(x).size === x.length;
function Brand({ footer = false }: { footer?: boolean }) { return <Link className={`brand ${footer ? "brand-footer" : ""}`} to="/" aria-label="VehicleSite home"><svg className="brand-mark" viewBox="0 0 44 36" aria-hidden="true"><path d="M1 1h10l11 28-6 6zM32 1h10L24 35l-5-11z" fill="currentColor" /></svg><span>VEHICLESITE<small>DRIVE YOUR NEXT CHAPTER</small></span></Link>; }
function RouteEffects({ motion }: { motion: boolean }) {
  const location = useLocation(); const pathname = location.pathname.replace(/\/+$/, "") || "/"; const previous = useRef(pathname);
  useEffect(() => {
    const title = navigation.find(([path]) => path === pathname)?.[1] || documentGroups.find(g => pathname === `/documents/${g.id}`)?.name || "Not found";
    document.title = `${title === "Home" ? "Drive your next chapter" : title} — VehicleSite`;
    if (previous.current !== pathname) { window.scrollTo({ top: 0, behavior: "instant" }); document.getElementById("main-content")?.focus({ preventScroll: true }); }
    previous.current = pathname;
    if (location.hash) { const id = decodeURIComponent(location.hash.slice(1)); requestAnimationFrame(() => document.getElementById(id)?.scrollIntoView({ behavior: motion ? "smooth" : "instant" })); }
  }, [pathname, location.hash, motion]);
  useEffect(() => {
    if (!motion || !("IntersectionObserver" in window)) { document.querySelectorAll(".will-reveal").forEach(el => el.classList.add("is-visible")); return; }
    const observer = new IntersectionObserver(entries => entries.forEach(entry => { if (entry.isIntersecting) { entry.target.classList.add("is-visible"); observer.unobserve(entry.target); } }), { threshold: .06 });
    const scan = () => document.querySelectorAll(".reveal:not(.will-reveal)").forEach(el => { el.classList.add("will-reveal"); observer.observe(el); });
    scan(); const mutations = new MutationObserver(scan); mutations.observe(document.getElementById("main-content")!, { childList: true, subtree: true });
    return () => { observer.disconnect(); mutations.disconnect(); document.querySelectorAll(".will-reveal").forEach(el => el.classList.remove("will-reveal")); };
  }, [motion, pathname]);
  return null;
}
function Header({ theme, changeTheme }: { theme: "dark" | "light"; changeTheme: () => void }) {
  const [open, setOpen] = useState(false); const { setModal, saved } = useSite(); const location = useLocation(); const menu = useRef<HTMLButtonElement>(null);
  useEffect(() => setOpen(false), [location.pathname, location.search]);
  useEffect(() => { const escape = (e: KeyboardEvent) => { if (e.key === "Escape" && open) { setOpen(false); menu.current?.focus(); } }; window.addEventListener("keydown", escape); return () => window.removeEventListener("keydown", escape); }, [open]);
  return <header className="site-header sales-header"><div className="scroll-progress" /><div className="header-inner container"><Brand /><nav id="primary-navigation" className={`primary-nav ${open ? "mobile-open" : ""}`} aria-label="Main navigation">{navigation.map(([path, label]) => <div className="nav-item" key={path}><NavLink to={path} end={path === "/"} onClick={() => setOpen(false)}>{label}</NavLink>{path === "/documents" && <div className="nav-submenu">{documentGroups.map(g => <Link key={g.id} to={`/documents/${g.id}`}>{g.name}<ArrowUpRight size={13} /></Link>)}</div>}</div>)}</nav><div className="header-actions"><button className="icon-button search-trigger" aria-label="Search website" title="Search (Ctrl / Command K)" onClick={() => { setOpen(false); setModal({ type: "search" }); }}><Search size={17} /></button><Link className="icon-button shortlist-link" to="/inventory?saved=1" aria-label={`Saved cars (${saved.length})`}><Heart size={17} />{saved.length > 0 && <span>{saved.length}</span>}</Link><button className="icon-button theme-toggle" aria-label={`Switch to ${theme === "dark" ? "light" : "dark"} theme`} onClick={changeTheme}>{theme === "dark" ? <Sun size={18} /> : <Moon size={18} />}</button><button ref={menu} className="icon-button menu-toggle" aria-label={open ? "Close menu" : "Open menu"} aria-expanded={open} aria-controls="primary-navigation" onClick={() => setOpen(!open)}>{open ? <X size={22} /> : <Menu size={22} />}</button></div></div></header>;
}
function Footer() {
  const { motion, setMotion, setModal } = useSite();
  return <footer className="site-footer"><div className="container"><div className="footer-top"><div><Brand footer /><p>Cars with character.<br />Numbers you can explore.<br />Your next set of keys.</p><span className="micro">AN AUTOMOTIVE RETAIL CONCEPT</span></div><div><h2>Find your next</h2>{navigation.slice(1).map(([path, label]) => <Link key={path} to={path}>{label}<ArrowUpRight size={13} /></Link>)}</div><div><h2>The paperwork</h2>{documentGroups.map(g => <Link key={g.id} to={`/documents/${g.id}`}>{g.name}<ArrowUpRight size={13} /></Link>)}</div><div className="footer-note"><span className="micro">IMAGINE THE POSSIBILITIES.</span><p>Fictional inventory and illustrative CAD prices. AI-generated concept images; video and document placeholders. This demo does not sell, reserve, finance, or book anything.</p><button className="text-link" onClick={() => setModal({ type: "search" })}><Command size={14} />Find your way around <kbd>⌘ K</kbd></button></div></div><div className="footer-wordmark" aria-hidden="true">VEHICLESITE<span>↗</span></div><div className="footer-bottom"><span>© {new Date().getFullYear()} VehicleSite. Showroom concept.</span><div><button onClick={() => setMotion(!motion)} aria-label={motion ? "Pause animations" : "Enable animations"}>{motion ? <Pause size={12} /> : <Play size={12} />}MOTION {motion ? "ON" : "OFF"}</button><span className="footer-status"><i />DEMO CONTENT</span><a href="#top" className="back-top" aria-label="Back to top">BACK TO TOP<ArrowUpRight size={14} /></a></div></div></div></footer>;
}
function Palette({ close }: { close: () => void }) {
  const [query, setQuery] = useState(""); const [active, setActive] = useState(0); const navigate = useNavigate(); const { setModal } = useSite();
  const entries = [...navigation.map(([to, label]) => ({ id: to, label, section: "Page", action: () => { close(); navigate(to); } })), ...documentGroups.map(g => ({ id: g.id, label: g.name, section: "Document folder", action: () => { close(); navigate(`/documents/${g.id}`); } })), ...vehicles.map(v => ({ id: v.id, label: v.name, section: `${v.year} · ${v.category} · Sample ${money(v.price)}`, action: () => setModal({ type: "vehicle", vehicle: v }) }))].filter(e => `${e.label} ${e.section}`.toLowerCase().includes(query.toLowerCase().trim())).slice(0, 10);
  return <Dialog title="Find your way around" onClose={close} className="palette-modal"><label className="palette-search"><Search size={22} /><input autoFocus role="combobox" aria-label="Search pages, cars, and documents" aria-autocomplete="list" aria-controls="palette-results" aria-expanded="true" aria-activedescendant={entries.length ? `palette-${active}` : undefined} placeholder="A car, a payment tool, a pickup detail…" value={query} onChange={e => { setQuery(e.target.value); setActive(0); }} onKeyDown={e => { if (e.key === "ArrowDown") { e.preventDefault(); setActive(a => Math.max(0, Math.min(entries.length - 1, a + 1))); } else if (e.key === "ArrowUp") { e.preventDefault(); setActive(a => Math.max(0, a - 1)); } else if (e.key === "Enter") { e.preventDefault(); entries[active]?.action(); } }} /><kbd>ESC</kbd></label><div id="palette-results" role="listbox" aria-label="Search results" className="palette-results">{entries.map((entry, i) => <button key={entry.id} id={`palette-${i}`} role="option" aria-selected={i === active} className={i === active ? "active" : ""} onMouseEnter={() => setActive(i)} onClick={entry.action}><span>{entry.label}<small>{entry.section}</small></span><ArrowUpRight size={18} /></button>)}</div>{!entries.length && <p className="palette-empty" role="status">No matches. Try “inventory”, “pickup”, or “Apex”.</p>}<div className="palette-footer micro"><span>↑ ↓ TO EXPLORE</span><span>↵ TO OPEN</span><span>ESC TO CLOSE</span></div></Dialog>;
}
function VehicleDetail({ vehicle: v, close }: { vehicle: Vehicle; close: () => void }) {
  const { saved, toggleSaved, comparison, toggleComparison, notify } = useSite(); const [view, setView] = useState(0); const [showLink, setShowLink] = useState(false);
  const gallery = v.gallery.filter(item => item.src);
  const activeImage = gallery[view] ?? gallery[0];
  const shareLink = new URL(`${import.meta.env.BASE_URL}inventory?vehicle=${encodeURIComponent(v.id)}`, window.location.origin).href;
  const copy = async () => { setShowLink(true); try { await navigator.clipboard.writeText(shareLink); notify("Car link copied. No personal information is included."); } catch { notify("Select and copy the car link shown below."); } };
  return <Dialog title="Vehicle details · Fictional listing" onClose={close} className="vehicle-modal"><div className="vehicle-detail-media sales-gallery"><MediaSlot key={activeImage?.src || v.id} vehicle={v} src={activeImage?.src ?? ""} label={activeImage?.label.toUpperCase() ?? "FICTIONAL VEHICLE CONCEPT"} /><span className="demo-badge">{v.stockNumber} / FICTIONAL VEHICLE</span></div>{gallery.length > 1 && <div className="sales-gallery-tabs" role="group" aria-label="Vehicle gallery">{gallery.map((item, i) => <button key={item.src} className={view === i ? "active" : ""} aria-pressed={view === i} onClick={() => setView(i)}>{item.label}</button>)}</div>}<div className="vehicle-detail-copy"><Eyebrow>{v.year} · {v.condition} · {v.stock} (sample)</Eyebrow><div className="sales-detail-title"><h2>{v.name}</h2><div><strong>{money(v.price)}</strong><small>Illustrative CAD · tax & fees extra</small></div></div><p>{v.description}</p><div className="spec-grid">{[["Mileage", distance(v.mileage)], ["Body", v.category], ["Energy", v.power], ["Drivetrain", v.drivetrain], ["Transmission", v.transmission], ["Seats", String(v.seats)]].map(([k, value]) => <div key={k}><span className="micro">{k}</span><strong>{value}</strong></div>)}</div><div className="sales-feature-list">{v.features.map(feature => <span key={feature}><Check size={14} />{feature}</span>)}</div><p className="sales-fineprint">All equipment and specifications are invented examples, not verified vehicle claims. History, inspection, and warranty records have not been supplied.</p><div className="detail-actions">{v.stock === "Available" ? <Link className="button button-gold" onClick={close} to={`/pickup?vehicle=${v.id}&purpose=test-drive`}>Plan a test drive<CalendarDays size={16} /></Link> : <span className="sales-unavailable">{v.stock === "Sold" ? "Sold example — visits disabled" : "Incoming example — visits not available yet"}</span>}<Link className="button button-subtle" onClick={close} to={`/buying?vehicle=${v.id}`}>Explore payments<ArrowUpRight size={16} /></Link><button className="button button-subtle" onClick={() => toggleSaved(v.id)} aria-pressed={saved.includes(v.id)}><Heart size={16} fill={saved.includes(v.id) ? "currentColor" : "none"} />{saved.includes(v.id) ? "Saved" : "Save car"}</button><button className="button button-subtle" onClick={() => toggleComparison(v.id)} aria-pressed={comparison.includes(v.id)}>{comparison.includes(v.id) ? <Check size={16} /> : <Plus size={16} />}Compare</button><button className="button button-subtle" onClick={copy}><Copy size={16} />Share car</button></div>{showLink && <label className="sales-field">Shareable car link<input readOnly value={shareLink} onFocus={e => e.target.select()} /></label>}<Link to="/documents/vehicle-records" onClick={close} className="text-link">What to ask about this car<ArrowUpRight size={15} /></Link></div></Dialog>;
}
function Comparison({ close }: { close: () => void }) {
  const { comparison, toggleComparison } = useSite(); const selected = vehicles.filter(v => comparison.includes(v.id));
  const rows: [string, (v: Vehicle) => string][] = [["Sample price (CAD)", v => money(v.price)], ["Model year", v => String(v.year)], ["Mileage", v => distance(v.mileage)], ["Condition", v => v.condition], ["Energy", v => v.power], ["Body", v => v.category], ["Seats", v => String(v.seats)], ["Stock (sample)", v => v.stock]];
  return <Dialog title="Your shortlist · Side-by-side comparison" onClose={close} className="comparison-modal"><Eyebrow>A clearer decision</Eyebrow><h2>The details make<br /><em>the difference.</em></h2><p>Compare up to three fictional cars. Sample prices exclude tax and fees.</p>{selected.length ? <div className="comparison-scroll"><table className="comparison-table"><caption className="sr-only">Fictional car comparison</caption><thead><tr><th scope="col">The details</th>{selected.map(v => <th scope="col" key={v.id}><MediaSlot vehicle={v} /><h3>{v.name}</h3><button className="text-link" aria-label={`Remove ${v.name} from comparison`} onClick={() => toggleComparison(v.id)}>Remove<X size={13} /></button></th>)}</tr></thead><tbody>{rows.map(([label, value]) => <tr key={label}><th scope="row">{label}</th>{selected.map(v => <td key={v.id}>{value(v)}</td>)}</tr>)}<tr><th scope="row">Explore the numbers</th>{selected.map(v => <td key={v.id}><Link className="text-link" onClick={close} to={`/buying?vehicle=${v.id}`}>Payment tools<ArrowUpRight size={14} /></Link></td>)}</tr><tr><th scope="row">Plan a visit</th>{selected.map(v => <td key={v.id}>{v.stock === "Available" ? <Link className="text-link" onClick={close} to={`/pickup?vehicle=${v.id}&purpose=test-drive`}>Draft a test drive<CalendarDays size={14} /></Link> : <span className="sales-unavailable">Visits unavailable for this sample</span>}</td>)}</tr></tbody></table></div> : <div className="empty-state"><p>Your comparison is empty.</p><button className="button button-gold" onClick={close}>Keep exploring</button></div>}</Dialog>;
}
function Modal({ modal, close }: { modal: NonNullable<ModalState>; close: () => void }) {
  if (modal.type === "search") return <Palette close={close} />;
  if (modal.type === "vehicle") return <VehicleDetail key={modal.vehicle.id} vehicle={modal.vehicle} close={close} />;
  if (modal.type === "compare") return <Comparison close={close} />;
  return <Dialog title="The showroom film · Placeholder" onClose={close} className="film-modal">{media.brandVideo ? <video className="brand-video" src={publicAsset(media.brandVideo)} poster={publicAsset(media.brandPoster) || undefined} controls playsInline /> : <div className="film-placeholder"><MediaSlot kind="city" label="SHOWROOM VIDEO PLACEHOLDER / 16:9" /><div><span className="film-placeholder-icon"><Play size={29} /></span><Eyebrow>Your next chapter</Eyebrow><h2>More than a car.<br /><em>A new beginning.</em></h2><p>Add your showroom film or inventory walkaround here.<br />This is an animated placeholder, not a playable video.</p></div></div>}</Dialog>;
}
function LegacyRoute({ to }: { to: string }) { const location = useLocation(); return <Navigate replace to={`${to}${location.search}${location.hash}`} />; }
function NotFound() { return <section className="container not-found"><Eyebrow>404 / A different road</Eyebrow><h1>This turn is<br /><em>still unwritten.</em></h1><p>The page you are looking for is not in this showroom.</p><Link to="/inventory" className="button button-gold">Explore the inventory<ArrowLeft size={17} /></Link></section>; }
export default function App() {
  const [theme, setTheme] = useStored<"dark" | "light">("vehiclesite.theme.v1", "dark", isTheme);
  const [motion, setMotion] = useStored("vehiclesite.motion.v1", !window.matchMedia("(prefers-reduced-motion: reduce)").matches, isBoolean);
  const [saved, setSaved] = useStored<string[]>("vehiclesite.saved.v1", [], validSaved);
  const [comparison, setComparison] = useState<string[]>([]); const [modal, setModal] = useState<ModalState>(null); const [toast, setToast] = useState(""); const timer = useRef<ReturnType<typeof setTimeout> | undefined>(undefined);
  const [params, setParams] = useSearchParams(); const location = useLocation();
  const notify = (text: string) => { clearTimeout(timer.current); setToast(text); timer.current = setTimeout(() => setToast(""), 4200); };
  const toggleSaved = (id: string) => { const has = saved.includes(id); setSaved(has ? saved.filter(x => x !== id) : [...saved, id]); notify(has ? "Car removed from your shortlist." : "Car saved in this browser. No alerts or reservations are created."); };
  const toggleComparison = (id: string) => { if (comparison.includes(id)) setComparison(comparison.filter(x => x !== id)); else if (comparison.length >= 3) notify("Compare up to three cars. Remove one to add another."); else setComparison([...comparison, id]); };
  const close = () => { setModal(null); if (params.has("vehicle") && location.pathname.replace(/\/+$/, "") === "/inventory") { const next = new URLSearchParams(params); next.delete("vehicle"); setParams(next, { replace: true }); } };
  useEffect(() => { if (location.pathname.replace(/\/+$/, "") === "/inventory") { const vehicle = vehicles.find(v => v.id === new URLSearchParams(location.search).get("vehicle")); if (vehicle) setModal({ type: "vehicle", vehicle }); } }, [location.pathname, location.search]);
  useEffect(() => { document.documentElement.dataset.theme = theme; document.querySelector('meta[name="theme-color"]')?.setAttribute("content", theme === "dark" ? "#111211" : "#f5f2eb"); }, [theme]);
  useEffect(() => { document.documentElement.dataset.motion = motion ? "on" : "off"; }, [motion]);
  useEffect(() => { const handle = (e: KeyboardEvent) => { if ((e.ctrlKey || e.metaKey) && e.key.toLowerCase() === "k") { e.preventDefault(); setModal(m => m?.type === "search" ? null : { type: "search" }); } }; window.addEventListener("keydown", handle); return () => { window.removeEventListener("keydown", handle); clearTimeout(timer.current); }; }, []);
  useEffect(() => { let frame = 0; const update = () => { cancelAnimationFrame(frame); frame = requestAnimationFrame(() => { const max = document.documentElement.scrollHeight - innerHeight; document.documentElement.style.setProperty("--scroll-progress", `${max > 0 ? scrollY / max : 0}`); }); }; window.addEventListener("scroll", update, { passive: true }); window.addEventListener("resize", update); update(); return () => { window.removeEventListener("scroll", update); window.removeEventListener("resize", update); cancelAnimationFrame(frame); }; }, []);
  return <SiteContext.Provider value={{ saved, toggleSaved, comparison, toggleComparison, clearComparison: () => setComparison([]), setModal, notify, motion, setMotion }}><div id="top" /><a href="#main-content" className="skip-link">Skip to main content</a><RouteEffects motion={motion} /><Header theme={theme} changeTheme={() => setTheme(theme === "dark" ? "light" : "dark")} /><main id="main-content" tabIndex={-1}><Routes><Route path="/" element={<Home />} /><Route path="/inventory" element={<Inventory />} /><Route path="/buying" element={<Buying />} /><Route path="/pickup" element={<Pickup />} /><Route path="/documents" element={<Documents />} /><Route path="/documents/:group" element={<Documents subpage />} /><Route path="/fleet" element={<LegacyRoute to="/inventory" />} /><Route path="/experiences" element={<LegacyRoute to="/buying" />} /><Route path="/concierge" element={<LegacyRoute to="/pickup" />} /><Route path="/documents/vehicle-guides" element={<LegacyRoute to="/documents/vehicle-records" />} /><Route path="/documents/booking-options" element={<LegacyRoute to="/documents/purchase-options" />} /><Route path="/documents/protection" element={<LegacyRoute to="/documents/pickup-essentials" />} /><Route path="*" element={<NotFound />} /></Routes></main><Footer />{comparison.length > 0 && <div className="compare-tray" aria-label="Comparison selection"><span className="compare-tray-icon"><SlidersHorizontal size={19} /></span><div><strong>{comparison.length} {comparison.length === 1 ? "car" : "cars"} selected</strong><span>A clearer view, side by side.</span></div><button className="button button-gold" onClick={() => setModal({ type: "compare" })}>Compare<ArrowRight size={16} /></button><button className="icon-button" aria-label="Clear comparison" onClick={() => setComparison([])}><X size={17} /></button></div>}<div className={`toast ${toast ? "show" : ""}`} role="status" aria-live="polite">{toast && <><Check size={16} />{toast}</>}</div>{modal && <Modal key={modal.type} modal={modal} close={close} />}</SiteContext.Provider>;
}
